%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% This script loads all files containing statistical data from all
% experiments perfromed, and generates the various figures appearing in the paper.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clear; 
close all;


PCP_24x_in_vivo = load('./Statistical data for plotting/PCP_24x_in_vivo.mat');
PCP_4x_in_vivo = load('./Statistical data for plotting/PCP_4x_QCP_5x_in_vivo.mat');

PP7_RBP_ONLY_background = load('./Statistical data for plotting/in_vivo_PCP_mCherry_only.mat');
PP7_RBP_ONLY_background = double(PP7_RBP_ONLY_background.pixels);

PCP_14x_MCP_15x_PROTEIN = load('./Statistical data for plotting/PCP_14x_MCP_15x_PROTEIN.mat');
PCP_3x_PROTEIN = load('./Statistical data for plotting/PCP_3x_PROTEIN.mat');
PCP_3x_MCP_3x_PROTEIN = load('./Statistical data for plotting/PCP_3x_MCP_3x_PROTEIN.mat');
PCP_4x_PROTEIN = load('./Statistical data for plotting/PCP_4x_PROTEIN.mat');
PCP_8x_PROTEIN = load('./Statistical data for plotting/PCP_8x_PROTEIN.mat');
PCP_4x_MCP_4x_PROTEIN = load('./Statistical data for plotting/PCP_4x_MCP_4x_PROTEIN.mat');

PCP_3x_RNA = load('./Statistical data for plotting/PCP_3x_RNA.mat');
PCP_3x_MCP_3x_RNA = load('./Statistical data for plotting/PCP_3x_MCP_3x_RNA.mat');
PCP_4x_RNA = load('./Statistical data for plotting/PCP_4x_RNA.mat');
PCP_8x_RNA = load('./Statistical data for plotting/PCP_8x_RNA.mat');
PCP_4x_MCP_4x_RNA = load('./Statistical data for plotting/PCP_4x_MCP_4x_RNA.mat');
PCP_14x_MCP_15x_RNA = load('./Statistical data for plotting/PCP_14x_MCP_15x_RNA.mat');

PCP_14x_MCP_15x_RNA_ONLY_GRANULES_RNASE = load('./Statistical data for plotting/PCP_14x_MCP_15x_RNA_ONLY_GRANULES_RNASE.mat');
PCP_14x_MCP_15x_RNA_ONLY_GRANULES = load('./Statistical data for plotting/PCP_14x_MCP_15x_RNA_ONLY_GRANULES.mat');

positive_amplitudes = struct(...
    'PCP_4x_in_vivo',PCP_4x_in_vivo.amp_pos_total,...
    'PCP_24x_in_vivo',PCP_24x_in_vivo.amp_pos_total,...
    'PCP_3x_PROTEIN',PCP_3x_PROTEIN.amp_pos_total,...
    'PCP_4x_PROTEIN',PCP_4x_PROTEIN.amp_pos_total,...
    'PCP_8x_PROTEIN',PCP_8x_PROTEIN.amp_pos_total,...
    'PCP_4x_MCP_4x_PROTEIN',PCP_4x_MCP_4x_PROTEIN.amp_pos_total,...
    'PCP_3x_MCP_3x_PROTEIN',PCP_3x_MCP_3x_PROTEIN.amp_pos_total,...
    'PCP_14x_MCP_15x_PROTEIN',PCP_14x_MCP_15x_PROTEIN.amp_pos_total,...
    'PCP_3x_RNA',PCP_3x_RNA.amp_pos_total,...
    'PCP_4x_RNA',PCP_4x_RNA.amp_pos_total,...
    'PCP_8x_RNA',PCP_8x_RNA.amp_pos_total,...
    'PCP_4x_MCP_4x_RNA',PCP_4x_MCP_4x_RNA.amp_pos_total,...
    'PCP_3x_MCP_3x_RNA',PCP_3x_MCP_3x_RNA.amp_pos_total,...
    'PCP_14x_MCP_15x_RNA',PCP_14x_MCP_15x_RNA.amp_pos_total,...
    'PCP_14x_MCP_15x_RNA_ONLY_GRANULES_RNASE',PCP_14x_MCP_15x_RNA_ONLY_GRANULES_RNASE.amp_pos_total,...
    'PCP_14x_MCP_15x_RNA_ONLY_GRANULES',PCP_14x_MCP_15x_RNA_ONLY_GRANULES.amp_pos_total);

negative_amplitudes = struct(...
    'PCP_4x_in_vivo',PCP_4x_in_vivo.amp_neg_total,...
    'PCP_24x_in_vivo',PCP_24x_in_vivo.amp_neg_total,...
    'PCP_3x_PROTEIN',PCP_3x_PROTEIN.amp_neg_total,...
    'PCP_4x_PROTEIN',PCP_4x_PROTEIN.amp_neg_total,...
    'PCP_8x_PROTEIN',PCP_8x_PROTEIN.amp_neg_total,...
    'PCP_4x_MCP_4x_PROTEIN',PCP_4x_MCP_4x_PROTEIN.amp_neg_total,...
    'PCP_3x_MCP_3x_PROTEIN',PCP_3x_MCP_3x_PROTEIN.amp_neg_total,...
    'PCP_14x_MCP_15x_PROTEIN',PCP_14x_MCP_15x_PROTEIN.amp_neg_total,...
    'PCP_3x_RNA',PCP_3x_RNA.amp_neg_total,...
    'PCP_4x_RNA',PCP_4x_RNA.amp_neg_total,...
    'PCP_8x_RNA',PCP_8x_RNA.amp_neg_total,...
    'PCP_4x_MCP_4x_RNA',PCP_4x_MCP_4x_RNA.amp_neg_total,...
    'PCP_3x_MCP_3x_RNA',PCP_3x_MCP_3x_RNA.amp_neg_total,...
    'PCP_14x_MCP_15x_RNA',PCP_14x_MCP_15x_RNA.amp_neg_total,...
    'PCP_14x_MCP_15x_RNA_ONLY_GRANULES_RNASE',PCP_14x_MCP_15x_RNA_ONLY_GRANULES_RNASE.amp_neg_total,...
    'PCP_14x_MCP_15x_RNA_ONLY_GRANULES',PCP_14x_MCP_15x_RNA_ONLY_GRANULES.amp_neg_total);

duration_between_entry = struct(...
    'PCP_4x_in_vivo',PCP_4x_in_vivo.time_between_pos,...
    'PCP_24x_in_vivo',PCP_24x_in_vivo.time_between_pos,...
    'PCP_3x_PROTEIN',PCP_3x_PROTEIN.time_between_pos,...
    'PCP_4x_PROTEIN',PCP_4x_PROTEIN.time_between_pos,...
    'PCP_8x_PROTEIN',PCP_8x_PROTEIN.time_between_pos,...
    'PCP_4x_MCP_4x_PROTEIN',PCP_4x_MCP_4x_PROTEIN.time_between_pos,...
    'PCP_3x_MCP_3x_PROTEIN',PCP_3x_MCP_3x_PROTEIN.time_between_pos,...
    'PCP_14x_MCP_15x_PROTEIN',PCP_14x_MCP_15x_PROTEIN.time_between_pos,...
    'PCP_3x_RNA',PCP_3x_RNA.time_between_pos,...
    'PCP_4x_RNA',PCP_4x_RNA.time_between_pos,...
    'PCP_8x_RNA',PCP_8x_RNA.time_between_pos,...
    'PCP_4x_MCP_4x_RNA',PCP_4x_MCP_4x_RNA.time_between_pos,...
    'PCP_3x_MCP_3x_RNA',PCP_3x_MCP_3x_RNA.time_between_pos,...
    'PCP_14x_MCP_15x_RNA',PCP_14x_MCP_15x_RNA.time_between_pos,...
    'PCP_14x_MCP_15x_RNA_ONLY_GRANULES_RNASE',PCP_14x_MCP_15x_RNA_ONLY_GRANULES_RNASE.time_between_pos,...
    'PCP_14x_MCP_15x_RNA_ONLY_GRANULES',PCP_14x_MCP_15x_RNA_ONLY_GRANULES.time_between_pos);

duration_between_exit = struct(...
    'PCP_4x_in_vivo',PCP_4x_in_vivo.time_between_neg,...
    'PCP_24x_in_vivo',PCP_24x_in_vivo.time_between_neg,...
    'PCP_3x_PROTEIN',PCP_3x_PROTEIN.time_between_neg,...
    'PCP_4x_PROTEIN',PCP_4x_PROTEIN.time_between_neg,...
    'PCP_8x_PROTEIN',PCP_8x_PROTEIN.time_between_neg,...
    'PCP_4x_MCP_4x_PROTEIN',PCP_4x_MCP_4x_PROTEIN.time_between_neg,...
    'PCP_3x_MCP_3x_PROTEIN',PCP_3x_MCP_3x_PROTEIN.time_between_neg,...
    'PCP_14x_MCP_15x_PROTEIN',PCP_14x_MCP_15x_PROTEIN.time_between_neg,...
    'PCP_3x_RNA',PCP_3x_RNA.time_between_neg,...
    'PCP_4x_RNA',PCP_4x_RNA.time_between_neg,...
    'PCP_8x_RNA',PCP_8x_RNA.time_between_neg,...
    'PCP_4x_MCP_4x_RNA',PCP_4x_MCP_4x_RNA.time_between_neg,...
    'PCP_3x_MCP_3x_RNA',PCP_3x_MCP_3x_RNA.time_between_neg,...
    'PCP_14x_MCP_15x_RNA',PCP_14x_MCP_15x_RNA.time_between_neg,...
    'PCP_14x_MCP_15x_RNA_ONLY_GRANULES_RNASE',PCP_14x_MCP_15x_RNA_ONLY_GRANULES_RNASE.time_between_neg,...
    'PCP_14x_MCP_15x_RNA_ONLY_GRANULES',PCP_14x_MCP_15x_RNA_ONLY_GRANULES.time_between_neg);

meanFluorescence = struct(...
    'PCP_4x_in_vivo',PCP_4x_in_vivo.meanmRNA,...
    'PCP_24x_in_vivo',PCP_24x_in_vivo.meanmRNA,...
    'PCP_3x_PROTEIN',PCP_3x_PROTEIN.meanmRNA,...
    'PCP_4x_PROTEIN',PCP_4x_PROTEIN.meanmRNA,...
    'PCP_8x_PROTEIN',PCP_8x_PROTEIN.meanmRNA,...
    'PCP_4x_MCP_4x_PROTEIN',PCP_4x_MCP_4x_PROTEIN.meanmRNA,...
    'PCP_3x_MCP_3x_PROTEIN',PCP_3x_MCP_3x_PROTEIN.meanmRNA,...
    'PCP_14x_MCP_15x_PROTEIN',PCP_14x_MCP_15x_PROTEIN.meanmRNA,...
    'PCP_3x_RNA',PCP_3x_RNA.meanmRNA,...
    'PCP_4x_RNA',PCP_4x_RNA.meanmRNA,...
    'PCP_8x_RNA',PCP_8x_RNA.meanmRNA,...
    'PCP_4x_MCP_4x_RNA',PCP_4x_MCP_4x_RNA.meanmRNA,...
    'PCP_3x_MCP_3x_RNA',PCP_3x_MCP_3x_RNA.meanmRNA,...
    'PCP_14x_MCP_15x_RNA',PCP_14x_MCP_15x_RNA.meanmRNA,...
    'PCP_14x_MCP_15x_RNA_ONLY_GRANULES_RNASE',PCP_14x_MCP_15x_RNA_ONLY_GRANULES_RNASE.meanmRNA,...
    'PCP_14x_MCP_15x_RNA_ONLY_GRANULES',PCP_14x_MCP_15x_RNA_ONLY_GRANULES.meanmRNA);

in_vivo_mean_spot_intensity = struct(...
    'PCP_4x_in_vivo',PCP_4x_in_vivo.mean_raw_measure,...
    'PCP_24x_in_vivo',PCP_24x_in_vivo.mean_raw_measure);

in_vivo_mean_cell_intensity = struct(...
    'PCP_4x_in_vivo',PCP_4x_in_vivo.background_mean,...
    'PCP_24x_in_vivo',PCP_24x_in_vivo.background_mean);


%% Granule size comparison
% Plots size comparison between granules
% - load image files
% - generate binary image based on threshold value
% - find connected components 

PCP_4x_image_data = imread('./Data for granule size comaprison/PCP_4x_RNA_only.png');
PCP_8x_image_data = imread('./Data for granule size comaprison/PCP_8x_RNA_only.png');
PCP_3x_MCP_3x_image_data = imread('./Data for granule size comaprison/PCP_3x_MCP_3x_RNA_only.png');
PCP_4x_MCP_4x_image_data = imread('./Data for granule size comaprison/PCP_4x_MCP_4x_RNA_only.png');
PCP_14x_MCP_15x_image_data = imread('./Data for granule size comaprison/PCP_14x_MCP_15x_RNA_only.png');

binary_image = zeros(size(PCP_4x_image_data));
binary_image(PCP_4x_image_data > 125) = 1; % Threshold selected manually
connected_components = bwconncomp(binary_image);
PCP_4x_measurements = regionprops(connected_components,'Area');

binary_image = zeros(size(PCP_8x_image_data));
binary_image(PCP_8x_image_data > 110) = 1; % Threshold selected manually
connected_components = bwconncomp(binary_image);
PCP_8x_measurements = regionprops(connected_components,'Area');

binary_image = zeros(size(PCP_3x_MCP_3x_image_data));
binary_image(PCP_3x_MCP_3x_image_data > 90) = 1; % Threshold selected manually
connected_components = bwconncomp(binary_image);
PCP_3x_MCP_3x_measurements = regionprops(connected_components,'Area');

binary_image = zeros(size(PCP_4x_MCP_4x_image_data));
binary_image(PCP_4x_MCP_4x_image_data > 150) = 1; % Threshold selected manually
connected_components = bwconncomp(binary_image);
PCP_4x_MCP_4x_measurements = regionprops(connected_components,'Area');

binary_image = zeros(size(PCP_14x_MCP_15x_image_data));
binary_image(PCP_14x_MCP_15x_image_data > 120) = 1; % Threshold selected manually
connected_components = bwconncomp(binary_image);
PCP_14x_MCP_15x_measurements = regionprops(connected_components,'Area');

PCP_4x_measurements = struct2array(PCP_4x_measurements);
PCP_8x_measurements = struct2array(PCP_8x_measurements);
PCP_3x_MCP_3x_measurements = struct2array(PCP_3x_MCP_3x_measurements);
PCP_4x_MCP_4x_measurements = struct2array(PCP_4x_MCP_4x_measurements);
PCP_14x_MCP_15x_measurements = struct2array(PCP_14x_MCP_15x_measurements);

% p value calculation
[~,p] = ttest2(PCP_4x_measurements,PCP_8x_measurements) 
[~,p] = ttest2(PCP_4x_measurements,PCP_3x_MCP_3x_measurements)
[~,p] = ttest2(PCP_4x_measurements,PCP_4x_MCP_4x_measurements) 
[~,p] = ttest2(PCP_4x_measurements,PCP_14x_MCP_15x_measurements) 
[~,p] = ttest2(PCP_3x_MCP_3x_measurements,PCP_14x_MCP_15x_measurements) 
[~,p] = ttest2(PCP_3x_MCP_3x_measurements,PCP_4x_MCP_4x_measurements) 
[~,p] = ttest2(PCP_3x_MCP_3x_measurements,PCP_8x_measurements)
[~,p] = ttest2(PCP_8x_measurements,PCP_14x_MCP_15x_measurements)
[~,p] = ttest2(PCP_8x_measurements,PCP_4x_MCP_4x_measurements)
[~,p] = ttest2(PCP_4x_MCP_4x_measurements,PCP_14x_MCP_15x_measurements)

g4 = repmat({'PCP-4x'},length(PCP_4x_measurements),1);
g33 = repmat({'PCP-3x_MCP_3x'},length(PCP_3x_MCP_3x_measurements),1);
g8 = repmat({'PCP-8x'},length(PCP_8x_measurements),1);
g44 = repmat({'PCP-4x_MCP_4x'},length(PCP_4x_MCP_4x_measurements),1);
g1415 = repmat({'PCP-14x_MCP_15x'},length(PCP_14x_MCP_15x_measurements),1);
g = [g4; g33; g8; g44; g1415];

boxplot([PCP_4x_measurements,...
    PCP_3x_MCP_3x_measurements,...
    PCP_8x_measurements,...
    PCP_4x_MCP_4x_measurements...
    ,PCP_14x_MCP_15x_measurements],g);
hold on;
ylim([-5,140]);
yt = get(gca, 'YTick');
xt = get(gca, 'XTick');
% plot astrixes where P values are significant
plot(xt([1 5]), [1 1]*120, '-k',  mean(xt([1 5])), 125, '*k')
plot(xt([1 3]), [1 1]*110, '-k',  mean(xt([1 3])), 115, '*k')
plot([2.05 2.95], [1 1]*100, '-k',  mean([2.05 2.95]), 105, '*k')
plot([3.05 3.95], [1 1]*100, '-k',  mean([3.05 3.95]), 105, '*k')
plot([4.05 4.95], [1 1]*100, '-k',  mean([4.05 4.95]), 105, '*k')


%% RNA-protein granules protein mean fluorescence
figure;
x = [meanFluorescence.PCP_3x_PROTEIN,...
    meanFluorescence.PCP_3x_MCP_3x_PROTEIN,...
    meanFluorescence.PCP_4x_PROTEIN,...
    meanFluorescence.PCP_4x_MCP_4x_PROTEIN,...
    meanFluorescence.PCP_8x_PROTEIN,...
    meanFluorescence.PCP_14x_MCP_15x_PROTEIN];
g = [repmat({'PCP-3x'},length(meanFluorescence.PCP_3x_PROTEIN),1);...
    repmat({'PCP-3x_MCP-3x'},length(meanFluorescence.PCP_3x_MCP_3x_PROTEIN),1);...
    repmat({'PCP-4x'},length(meanFluorescence.PCP_4x_PROTEIN),1);...
    repmat({'PCP-4x_MCP-4x'},length(meanFluorescence.PCP_4x_MCP_4x_PROTEIN),1);...
    repmat({'PCP-8x'},length(meanFluorescence.PCP_8x_PROTEIN),1);...
    repmat({'PCP-14x_MCP-15x'},length(meanFluorescence.PCP_14x_MCP_15x_PROTEIN),1)];
boxplot(x,g);
ylim([0,6000]);
ylabel('Fluorescence intensity');
title('Mean granule fluorescence (585 nm)');

%% RNA fluorescence difference between RNA-protein granules and RNA granules
% Load RNA (488 nm) fluorescence measurements 
median_measurements_3x_RNA_protein = xlsread('./Statistical data for plotting/median_measurements_3x_RNA_protein.csv');
median_measurements_3x_3x = xlsread('./Statistical data for plotting/median_measurements_3_3.csv');
median_measurements_3x_3x_RNA_protein = xlsread('./Statistical data for plotting/median_measurements_3_3_RNA_protein.csv');
median_measurements_4x = xlsread('./Statistical data for plotting/median_measurements_4x.csv');
median_measurements_4x_RNA_protein = xlsread('./Statistical data for plotting/median_measurements_4x_RNA_protein.csv');
median_measurements_4x_4x = xlsread('./Statistical data for plotting/median_measurements_4_4.csv');
median_measurements_4x_4x_RNA_protein = xlsread('./Statistical data for plotting/median_measurements_4_4_RNA_protein.csv');
median_measurements_8x = xlsread('./Statistical data for plotting/median_measurements_8x.csv');
median_measurements_8x_RNA_protein = xlsread('./Statistical data for plotting/median_measurements_8x_RNA_protein.csv');
median_measurements_14x_15x = xlsread('./Statistical data for plotting/median_measurements_14_15.csv');
median_measurements_14x_15x_RNA_protein = xlsread('./Statistical data for plotting/median_measurements_14_15_RNA_protein.csv');

% Estimated uracil quantity in slncRNA sequences
% Intensity data is noramlized by these numbers to get a standardaized
% measurement and to reduce noise.
% 3x - 56
% 3x-3x - 91
% 4x - 86
% 4x-4x - 117
% 8x - 122
% 14x-15x - 326

% calculate change percentage
percent_change_3_3 = 100*(median(median_measurements_3x_3x_RNA_protein(:,4))/(0.35*91)-...
    median(median_measurements_3x_3x(:,4))/(0.35*91))/(median(median_measurements_3x_3x(:,4))/(0.35*91));
percent_change_4_4 = 100*(median(median_measurements_4x_4x_RNA_protein(:,4))/(0.35*117)-...
    median(median_measurements_4x_4x(:,4))/(0.35*117))/(median(median_measurements_4x_4x(:,4))/(0.35*117));
percent_change_14_15 = 100*(median(median_measurements_14x_15x_RNA_protein(:,4))/(0.35*326)-...
    median(median_measurements_14x_15x(:,4))/(0.35*326))/(median(median_measurements_14x_15x(:,4))/(0.35*326));
percent_change_4 = 100*(median(median_measurements_4x_RNA_protein(:,4))/(0.35*86)-...
    median(median_measurements_4x(:,4))/(0.35*86))/(median(median_measurements_4x(:,4))/(0.35*86));
percent_change_8 = 100*(median(median_measurements_8x_RNA_protein(:,4))/(0.35*122)-...
    median(median_measurements_8x(:,4))/(0.35*122))/(median(median_measurements_8x(:,4))/(0.35*122));

figure; 
subplot(2,1,2);
scatter([2:6],[percent_change_4,percent_change_3_3,percent_change_4_4,percent_change_8,percent_change_14_15])
xlim([0.5,6.5]);
ylim([0,115]);

x_RNA = [2:6];
x_RNP = [1:6];
y_RNA = [median(median_measurements_4x(:,4))/(0.35*86),...
    median(median_measurements_3x_3x(:,4))/(0.35*91),...
    median(median_measurements_4x_4x(:,4))/(0.35*117),...
    median(median_measurements_8x(:,4))/(0.35*122),...
    median(median_measurements_14x_15x(:,4))/(0.35*326)];
y_RNP = [median(median_measurements_3x_RNA_protein(:,4))/(0.35*56),...
    median(median_measurements_4x_RNA_protein(:,4))/(0.35*86),...
    median(median_measurements_3x_3x_RNA_protein(:,4))/(0.35*91),...
    median(median_measurements_4x_4x_RNA_protein(:,4))/(0.35*117),...
    median(median_measurements_8x_RNA_protein(:,4))/(0.35*122),...
    median(median_measurements_14x_15x_RNA_protein(:,4))/(0.35*326)];

err_RNA = [std((median_measurements_4x(:,4)/(0.35*86)))/sqrt(length( median_measurements_4x(:,4))),...
    std((median_measurements_3x_3x(:,4)/(0.35*91)))/sqrt(length( median_measurements_3x_3x(:,4))),...
    std((median_measurements_4x_4x(:,4)/(0.35*117)))/sqrt(length( median_measurements_4x_4x(:,4))),...
    std((median_measurements_8x(:,4)/(0.35*122)))/sqrt(length( median_measurements_8x(:,4))),...
    std((median_measurements_14x_15x(:,4)/(0.35*326)))/sqrt( length(median_measurements_14x_15x(:,4)))];

err_RNP = [std((median_measurements_3x_RNA_protein(:,4)/(0.35*56)))/sqrt(length(median_measurements_3x_RNA_protein(:,4))),...
    std((median_measurements_4x_RNA_protein(:,4)/(0.35*86)))/sqrt(length(median_measurements_4x_RNA_protein(:,4))),...
    std((median_measurements_3x_3x_RNA_protein(:,4)/(0.35*91)))/sqrt(length(median_measurements_3x_3x_RNA_protein(:,4))),...
    std((median_measurements_4x_4x_RNA_protein(:,4)/(0.35*117)))/sqrt(length(median_measurements_4x_4x_RNA_protein(:,4))),...
    std(median_measurements_8x_RNA_protein(:,4)/(0.35*122))/sqrt(length(rmoutliers(median_measurements_8x_RNA_protein(:,4)))),...
    std((median_measurements_14x_15x_RNA_protein(:,4)/(0.35*326)))/sqrt(length(median_measurements_14x_15x_RNA_protein(:,4)))];
subplot(2,1,1);
errorbar(x_RNA,y_RNA,err_RNA,'o'); hold on;
errorbar(x_RNP,y_RNP,err_RNP,'o'); 
% ylim([200,900]);
xlim([0.5,6.5]);
legend('RNA granules','RNA protein granules');

%% RNAse Amplitude comparison

backLength = 7; % original is 7 pixels
folderPath = ['./backLength_',num2str(backLength),'/'];


no_RNAse_data = load('./Statistical data for plotting/RNAse/amplitudes_with_times_no_RNAse.mat');
RNAse_data = load('./Statistical data for plotting/RNAse/amplitudes_with_times_RNAse.mat');


time0_30_neg_RNAse = RNAse_data.amp_neg_total_with_signal_num(RNAse_data.amp_neg_total_with_signal_num(:,1)>0 &...
    RNAse_data.amp_neg_total_with_signal_num(:,1)<=180,2);
time30_60_neg_RNAse = RNAse_data.amp_neg_total_with_signal_num(RNAse_data.amp_neg_total_with_signal_num(:,1)>180 &...
    RNAse_data.amp_neg_total_with_signal_num(:,1)<=360,2);
time0_30_neg_no_RNAse = no_RNAse_data.amp_neg_total_with_signal_num(no_RNAse_data.amp_neg_total_with_signal_num(:,1)>0 &...
    no_RNAse_data.amp_neg_total_with_signal_num(:,1)<=180,2);
time30_60_neg_no_RNAse = no_RNAse_data.amp_neg_total_with_signal_num(no_RNAse_data.amp_neg_total_with_signal_num(:,1)>180 &...
    no_RNAse_data.amp_neg_total_with_signal_num(:,1)<=360,2);

time0_30_pos_RNAse = RNAse_data.amp_pos_total_with_signal_num(RNAse_data.amp_pos_total_with_signal_num(:,1)>0 &...
    RNAse_data.amp_pos_total_with_signal_num(:,1)<=180,2);
time30_60_pos_RNAse = RNAse_data.amp_pos_total_with_signal_num(RNAse_data.amp_pos_total_with_signal_num(:,1)>180 &...
    RNAse_data.amp_pos_total_with_signal_num(:,1)<=360,2);
time0_30_pos_no_RNAse = no_RNAse_data.amp_pos_total_with_signal_num(no_RNAse_data.amp_pos_total_with_signal_num(:,1)>0 &...
    no_RNAse_data.amp_pos_total_with_signal_num(:,1)<=180,2);
time30_60_pos_no_RNAse = no_RNAse_data.amp_pos_total_with_signal_num(no_RNAse_data.amp_pos_total_with_signal_num(:,1)>180 &...
    no_RNAse_data.amp_pos_total_with_signal_num(:,1)<=360,2);


figure;
x = [(time0_30_pos_no_RNAse/(326*0.35));...
    (time30_60_pos_no_RNAse/(326*0.35));...
    (time0_30_pos_RNAse/(326*0.35));...
    (time30_60_pos_RNAse/(326*0.35));...
    (abs(time0_30_neg_no_RNAse/(326*0.35)));...
    (abs(time30_60_neg_no_RNAse/(326*0.35)));...
    (abs(time0_30_neg_RNAse/(326*0.35)));...
    (abs(time30_60_neg_RNAse/(326*0.35)))];
g1 = repmat({'Entry RNAse - [0-30]'},length((time0_30_pos_no_RNAse)),1);
g2 = repmat({'Entry RNAse - [30-60]'},length((time30_60_pos_no_RNAse)),1);
g3 = repmat({'Entry RNAse + [0-30]'},length((time0_30_pos_RNAse)),1);
g4 = repmat({'Entry RNAse + [30-60]'},length((time30_60_pos_RNAse)),1);
g5 = repmat({'Exit RNAse - [0-30]'},length((time0_30_neg_no_RNAse)),1);
g6 = repmat({'Exit RNAse - [30-60]'},length((time30_60_neg_no_RNAse)),1);
g7 = repmat({'Exit RNAse + [0-30]'},length((time0_30_neg_RNAse)),1);
g8 = repmat({'Exit RNAse + [30-60]'},length((time30_60_neg_RNAse)),1);
g = [g1; g2; g3; g4; g5; g6; g7; g8];
boxplot(x,g); ylim([0,5]);
title('amplitudes - Normal vs. RNAse');

%% Protein burst amplitude boxplots

x = [(positive_amplitudes.PCP_3x_PROTEIN);...
    (positive_amplitudes.PCP_4x_PROTEIN);...
    (positive_amplitudes.PCP_8x_PROTEIN);...
    (positive_amplitudes.PCP_3x_MCP_3x_PROTEIN);...
    (positive_amplitudes.PCP_4x_MCP_4x_PROTEIN);...
    (positive_amplitudes.PCP_14x_MCP_15x_PROTEIN)];

g3 = repmat({'PCP-3x'},length(positive_amplitudes.PCP_3x_PROTEIN),1);
g4 = repmat({'PCP-4x'},length(positive_amplitudes.PCP_4x_PROTEIN),1);
g8 = repmat({'PCP-8x'},length(positive_amplitudes.PCP_8x_PROTEIN),1);
g33 = repmat({'PCP-3x_MCP_3x'},length(positive_amplitudes.PCP_3x_MCP_3x_PROTEIN),1);
g44 = repmat({'PCP-4x_MCP_4x'},length(positive_amplitudes.PCP_4x_MCP_4x_PROTEIN),1);
g1415 = repmat({'PCP-14x_MCP_15x'},length(positive_amplitudes.PCP_14x_MCP_15x_PROTEIN),1);
g = [g3; g4; g8; g33; g44; g1415];

figure; boxplot(x,g);
ylim([-250,3000]);

%% Time between significant events boxplots

x0 = [(duration_between_exit.PCP_3x_PROTEIN);...
    (duration_between_entry.PCP_3x_PROTEIN)];
g0 = [repmat({'Negative'},length(duration_between_exit.PCP_3x_PROTEIN),1);...
    repmat({'Positive'},length(duration_between_entry.PCP_3x_PROTEIN),1)];

x1 = [(duration_between_exit.PCP_4x_PROTEIN);...
    (duration_between_entry.PCP_4x_PROTEIN)];
g1 = [repmat({'Negative'},length(duration_between_exit.PCP_4x_PROTEIN),1);...
    repmat({'Positive'},length(duration_between_entry.PCP_4x_PROTEIN),1)];

x2 = [(duration_between_exit.PCP_8x_PROTEIN);...
    (duration_between_entry.PCP_8x_PROTEIN)];
g2 = [repmat({'Negative'},length(duration_between_exit.PCP_8x_PROTEIN),1);...
    repmat({'Positive'},length(duration_between_entry.PCP_8x_PROTEIN),1)];

x3 = [(duration_between_exit.PCP_3x_MCP_3x_PROTEIN);...
    (duration_between_entry.PCP_3x_MCP_3x_PROTEIN)];
g3 = [repmat({'Negative'},length(duration_between_exit.PCP_3x_MCP_3x_PROTEIN),1);...
    repmat({'Positive'},length(duration_between_entry.PCP_3x_MCP_3x_PROTEIN),1)];

x4 = [(duration_between_exit.PCP_4x_MCP_4x_PROTEIN);...
    (duration_between_entry.PCP_4x_MCP_4x_PROTEIN)];
g4 = [repmat({'Negative'},length(duration_between_exit.PCP_4x_MCP_4x_PROTEIN),1);...
    repmat({'Positive'},length(duration_between_entry.PCP_4x_MCP_4x_PROTEIN),1)];

x5 = [(duration_between_exit.PCP_14x_MCP_15x_PROTEIN);...
    (duration_between_entry.PCP_14x_MCP_15x_PROTEIN)];
g5 = [repmat({'Negative'},length(duration_between_exit.PCP_14x_MCP_15x_PROTEIN),1);...
    repmat({'Positive'},length(duration_between_entry.PCP_14x_MCP_15x_PROTEIN),1)];

figure;
subplot(1,6,1); boxplot(x0,g0,'Colors','rg'); ylim([0,60]); title('PP7-3x'); ylabel('Time [min]');
subplot(1,6,3); boxplot(x1,g1,'Colors','rg'); ylim([0,60]); title('PP7-4x'); 
subplot(1,6,5); boxplot(x2,g2,'Colors','rg'); ylim([0,60]); title('PP7-8x');
subplot(1,6,2); boxplot(x3,g3,'Colors','rg'); ylim([0,60]); title('PP7-3x-MS2-3x');
subplot(1,6,4); boxplot(x4,g4,'Colors','rg'); ylim([0,60]); title('PP7-4x-MS2-4x');
subplot(1,6,6); boxplot(x5,g5,'Colors','rg'); ylim([0,60]); title('PP7-14x-MS2-15x');

figure;
subplot(2,1,1);
errorbar([1:6],[median(duration_between_exit.PCP_3x_PROTEIN),...
    median(duration_between_exit.PCP_3x_MCP_3x_PROTEIN),...
    median(duration_between_exit.PCP_4x_PROTEIN),...
    median(duration_between_exit.PCP_4x_MCP_4x_PROTEIN),...
    median(duration_between_exit.PCP_8x_PROTEIN),...
    median(duration_between_exit.PCP_14x_MCP_15x_PROTEIN)],...
    [std(duration_between_exit.PCP_3x_PROTEIN)/sqrt(length(duration_between_exit.PCP_3x_PROTEIN)),...
    std(duration_between_exit.PCP_3x_MCP_3x_PROTEIN)/sqrt(length(duration_between_exit.PCP_3x_MCP_3x_PROTEIN)),...
    std(duration_between_exit.PCP_4x_PROTEIN)/sqrt(length(duration_between_exit.PCP_4x_PROTEIN)),...
    std(duration_between_exit.PCP_4x_MCP_4x_PROTEIN)/sqrt(length(duration_between_exit.PCP_4x_MCP_4x_PROTEIN)),...
    std(duration_between_exit.PCP_8x_PROTEIN)/sqrt(length(duration_between_exit.PCP_8x_PROTEIN)),...
    std(duration_between_exit.PCP_14x_MCP_15x_PROTEIN)/sqrt(length(duration_between_exit.PCP_14x_MCP_15x_PROTEIN))],'o','color','r')
xlim([0,7]); ylim([0,25]);
ylabel('Time [min]'); title('Time between exit events');

subplot(2,1,2);
errorbar([1:6],[median(duration_between_entry.PCP_3x_PROTEIN),...
    median(duration_between_entry.PCP_3x_MCP_3x_PROTEIN),...
    median(duration_between_entry.PCP_4x_PROTEIN),...
    median(duration_between_entry.PCP_4x_MCP_4x_PROTEIN),...
    median(duration_between_entry.PCP_8x_PROTEIN),...
    median(duration_between_entry.PCP_14x_MCP_15x_PROTEIN)],...
    [std(duration_between_entry.PCP_3x_PROTEIN)/sqrt(length(duration_between_entry.PCP_3x_PROTEIN)),...
    std(duration_between_entry.PCP_3x_MCP_3x_PROTEIN)/sqrt(length(duration_between_entry.PCP_3x_MCP_3x_PROTEIN)),...
    std(duration_between_entry.PCP_4x_PROTEIN)/sqrt(length(duration_between_entry.PCP_4x_PROTEIN)),...
    std(duration_between_entry.PCP_4x_MCP_4x_PROTEIN)/sqrt(length(duration_between_entry.PCP_4x_MCP_4x_PROTEIN)),...
    std(duration_between_entry.PCP_8x_PROTEIN)/sqrt(length(duration_between_entry.PCP_8x_PROTEIN)),...
    std(duration_between_entry.PCP_14x_MCP_15x_PROTEIN)/sqrt(length(duration_between_entry.PCP_14x_MCP_15x_PROTEIN))],'o','color','g')
xlim([0,7]); ylim([0,25]);
ylabel('Time [min]'); title('Time between entry events');

%% Protein and RNA content estimation

mean_molecules3 = meanFluorescence.PCP_3x_RNA/abs(median(negative_amplitudes.PCP_3x_RNA));
mean_molecules4 = meanFluorescence.PCP_4x_RNA/abs(median(negative_amplitudes.PCP_4x_RNA));
mean_molecules8 = meanFluorescence.PCP_8x_RNA/abs(median(negative_amplitudes.PCP_8x_RNA));
mean_molecules33 = meanFluorescence.PCP_3x_MCP_3x_RNA/abs(median(negative_amplitudes.PCP_3x_MCP_3x_RNA));
mean_molecules44 = meanFluorescence.PCP_4x_MCP_4x_RNA/abs(median(negative_amplitudes.PCP_4x_MCP_4x_RNA));
mean_molecules1415 = meanFluorescence.PCP_14x_MCP_15x_RNA/abs(median(negative_amplitudes.PCP_14x_MCP_15x_RNA));
figure;
x = [mean_molecules3, mean_molecules4, mean_molecules8, mean_molecules33,...
    mean_molecules44, mean_molecules1415];
g = [repmat({'PCP-3x'},length(mean_molecules3),1);...
    repmat({'PCP-4x'},length(mean_molecules4),1);...
    repmat({'PCP-8x'},length(mean_molecules8),1);...
    repmat({'PCP-3x_MCP-3x'},length(mean_molecules33),1);...
    repmat({'PCP-4x_MCP-4x'},length(mean_molecules44),1);...
    repmat({'PCP-14x_MCP-15x'},length(mean_molecules1415),1)];
boxplot(x,g);
title('RNA signal intensity / mean(negative amplitudes)');
ylim([0,50]);

mean_molecules3 = meanFluorescence.PCP_3x_PROTEIN/abs(median(negative_amplitudes.PCP_3x_PROTEIN));
mean_molecules4 = meanFluorescence.PCP_4x_PROTEIN/abs(median(negative_amplitudes.PCP_4x_PROTEIN));
mean_molecules8 = meanFluorescence.PCP_8x_PROTEIN/abs(median(negative_amplitudes.PCP_8x_PROTEIN));
mean_molecules33 = meanFluorescence.PCP_3x_MCP_3x_PROTEIN/abs(median(negative_amplitudes.PCP_3x_MCP_3x_PROTEIN));
mean_molecules44 = meanFluorescence.PCP_4x_MCP_4x_PROTEIN/abs(median(negative_amplitudes.PCP_4x_MCP_4x_PROTEIN));
mean_molecules1415 = meanFluorescence.PCP_14x_MCP_15x_PROTEIN/abs(median(negative_amplitudes.PCP_14x_MCP_15x_PROTEIN));

figure;
x = [mean_molecules3, mean_molecules4, mean_molecules8, mean_molecules33,...
    mean_molecules44, mean_molecules1415];
g = [repmat({'PCP-3x'},length(mean_molecules3),1);...
    repmat({'PCP-4x'},length(mean_molecules4),1);...
    repmat({'PCP-8x'},length(mean_molecules8),1);...
    repmat({'PCP-3x_MCP-3x'},length(mean_molecules33),1);...
    repmat({'PCP-4x_MCP-4x'},length(mean_molecules44),1);...
    repmat({'PCP-14x_MCP-15x'},length(mean_molecules1415),1)];
boxplot(x,g);
title('Protein signal intensity / mean(negative amplitudes)');
ylim([0,50]);

%% Net slncRNA loss plot
figure;
scatter([1:6],...
    [(length(negative_amplitudes.PCP_3x_PROTEIN)-length(positive_amplitudes.PCP_3x_PROTEIN))/length(meanFluorescence.PCP_3x_PROTEIN);...
    (length(negative_amplitudes.PCP_4x_PROTEIN)-length(positive_amplitudes.PCP_4x_PROTEIN))/length(meanFluorescence.PCP_4x_PROTEIN);...
    (length(negative_amplitudes.PCP_8x_PROTEIN)-length(positive_amplitudes.PCP_8x_PROTEIN))/length(meanFluorescence.PCP_8x_PROTEIN);...
    (length(negative_amplitudes.PCP_3x_MCP_3x_PROTEIN)-length(positive_amplitudes.PCP_3x_MCP_3x_PROTEIN))/length(meanFluorescence.PCP_3x_MCP_3x_PROTEIN);...
    (length(negative_amplitudes.PCP_4x_MCP_4x_PROTEIN)-length(positive_amplitudes.PCP_4x_MCP_4x_PROTEIN))/length(meanFluorescence.PCP_4x_MCP_4x_PROTEIN);...
    (length(negative_amplitudes.PCP_14x_MCP_15x_PROTEIN)-length(positive_amplitudes.PCP_14x_MCP_15x_PROTEIN))/length(meanFluorescence.PCP_14x_MCP_15x_PROTEIN)]);
xlim([0,7]);

%% Titration experiment plot
% load data
titration_x10 = load('./Statistical data for plotting/Titration/titration_x10.mat');
titration_x1 = load('./Statistical data for plotting/Titration/titration_x1.mat');
titration_x100 = load('./Statistical data for plotting/Titration/titration_x100.mat');
% Amplitude boxplot

figure;
x = [positive_amplitudes.PCP_14x_MCP_15x_PROTEIN;...
    titration_x100.amp_pos_total;...
    titration_x1.amp_pos_total];
g = [10*ones(length(positive_amplitudes.PCP_14x_MCP_15x_PROTEIN),1);...
    100*ones(length(titration_x100.amp_pos_total),1);...
    1*ones(length(titration_x1.amp_pos_total),1)];
boxplot(x,g); ylim([0,1500]);
title('Positive amplitudes');
xlabel('Protein concentration / RNA concentration');
ylabel('Intensity [A.U]');


x0 = [titration_x1.time_between_neg;...
    titration_x1.time_between_pos];
g0 = [repmat({'Negative'},length(titration_x1.time_between_neg),1);...
    repmat({'Positive'},length(titration_x1.time_between_pos),1)];

x1 = [duration_between_exit.PCP_14x_MCP_15x_PROTEIN;...
    duration_between_entry.PCP_14x_MCP_15x_PROTEIN];
g1 = [repmat({'Negative'},length(duration_between_exit.PCP_14x_MCP_15x_PROTEIN),1);...
    repmat({'Positive'},length(duration_between_entry.PCP_14x_MCP_15x_PROTEIN),1)];

x2 = [titration_x100.time_between_neg;...
    titration_x100.time_between_pos];
g2 = [repmat({'Negative'},length(titration_x100.time_between_neg),1);...
    repmat({'Positive'},length(titration_x100.time_between_pos),1)];

figure;
subplot(1,3,1); boxplot(x0,g0,'Colors','rg'); ylim([0,60]); title('1');
subplot(1,3,2); boxplot(x1,g1,'Colors','rg'); ylim([0,60]); title('10');
subplot(1,3,3); boxplot(x2,g2,'Colors','rg'); ylim([0,60]); title('100');

%% mCherry vs. Cerulean competition
% load data
competition_14_15_red = load('./Statistical data for plotting/mCherry_cerulean/red_data.mat');
competition_14_15_blue = load('./Statistical data for plotting/mCherry_cerulean/blue_data.mat');


x0 = [competition_14_15_red.time_between_pos;...
    competition_14_15_blue.time_between_pos];
g0 = [repmat({'mCherry'},length(competition_14_15_red.time_between_pos),1);...
    repmat({'Cerulean'},length(competition_14_15_blue.time_between_pos),1)];
figure;
subplot(1,2,1)
boxplot(x0,g0,'Colors','br'); ylim([0,60]);
title('Time between entry events');

x0 = [competition_14_15_red.time_between_neg;...
    competition_14_15_blue.time_between_neg];
g0 = [repmat({'mCherry'},length(competition_14_15_red.time_between_neg),1);...
    repmat({'Cerulean'},length(competition_14_15_blue.time_between_neg),1)];

subplot(1,2,2)
boxplot(x0,g0,'Colors','br'); ylim([0,60]);
title('Time between exit events');

load('./Statistical data for plotting/mCherry_cerulean/amplitudes_with_times_blue.mat');

time0_20_neg_blue = amp_neg_total_with_signal_num(amp_neg_total_with_signal_num(:,1)>12 &...
    amp_neg_total_with_signal_num(:,1)<=120,2);
time20_40_neg_blue = amp_neg_total_with_signal_num(amp_neg_total_with_signal_num(:,1)>120 &...
    amp_neg_total_with_signal_num(:,1)<=240,2);
time40_60_neg_blue = amp_neg_total_with_signal_num(amp_neg_total_with_signal_num(:,1)>240 &...
    amp_neg_total_with_signal_num(:,1)<=360,2);

figure;
boxplot([time0_20_neg_blue;time20_40_neg_blue;time40_60_neg_blue],...
    [20*ones(length(time0_20_neg_blue),1);...
    40*ones(length(time20_40_neg_blue),1);...
    60*ones(length(time40_60_neg_blue),1)]);
title('Cerulean negative amplitudes');

time0_20_pos_blue = amp_pos_total_with_signal_num(amp_pos_total_with_signal_num(:,1)>12 &...
    amp_pos_total_with_signal_num(:,1)<=120,2);
time20_40_pos_blue = amp_pos_total_with_signal_num(amp_pos_total_with_signal_num(:,1)>120 &...
    amp_pos_total_with_signal_num(:,1)<=240,2);
time40_60_pos_blue = amp_pos_total_with_signal_num(amp_pos_total_with_signal_num(:,1)>240 &...
    amp_pos_total_with_signal_num(:,1)<=360,2);

figure;
boxplot([time0_20_pos_blue;time20_40_pos_blue;time40_60_pos_blue],...
    [20*ones(length(time0_20_pos_blue),1);...
    40*ones(length(time20_40_pos_blue),1);...
    60*ones(length(time40_60_pos_blue),1)]);
title('Cerulean positive amplitudes');


load('./Statistical data for plotting/mCherry_cerulean/amplitudes_with_times_red.mat');

time0_20_neg_red = amp_neg_total_with_signal_num(amp_neg_total_with_signal_num(:,1)>12 &...
    amp_neg_total_with_signal_num(:,1)<=120,2);
time20_40_neg_red = amp_neg_total_with_signal_num(amp_neg_total_with_signal_num(:,1)>120 &...
    amp_neg_total_with_signal_num(:,1)<=240,2);
time40_60_neg_red = amp_neg_total_with_signal_num(amp_neg_total_with_signal_num(:,1)>240 &...
    amp_neg_total_with_signal_num(:,1)<=360,2);

figure;
boxplot([time0_20_neg_red;time20_40_neg_red;time40_60_neg_red],...
    [20*ones(length(time0_20_neg_red),1);...
    40*ones(length(time20_40_neg_red),1);...
    60*ones(length(time40_60_neg_red),1)]);
title('mCherry negative amplitudes');

time0_20_pos_red = amp_pos_total_with_signal_num(amp_pos_total_with_signal_num(:,1)>12 &...
    amp_pos_total_with_signal_num(:,1)<=120,2);
time20_40_pos_red = amp_pos_total_with_signal_num(amp_pos_total_with_signal_num(:,1)>120 &...
    amp_pos_total_with_signal_num(:,1)<=240,2);
time40_60_pos_red = amp_pos_total_with_signal_num(amp_pos_total_with_signal_num(:,1)>240 &...
    amp_pos_total_with_signal_num(:,1)<=360,2);

figure;
boxplot([time0_20_pos_red;time20_40_pos_red;time40_60_pos_red],...
    [20*ones(length(time0_20_pos_red),1);...
    40*ones(length(time20_40_pos_red),1);...
    60*ones(length(time40_60_pos_red),1)]);
title('mCherry positive amplitudes');

subplot(1,3,1);
sgtitle('Entry events');
bar([1,2],[length(time0_20_pos_red);...
    length(time0_20_pos_blue)]); ylim([0,45]);
title('Time 2-20 min');
subplot(1,3,2);
bar([1,2],[length(time20_40_pos_red);...
    length(time20_40_pos_blue)]); ylim([0,45]);
title('Time 20-40 min');
subplot(1,3,3);
bar([1,2],[length(time40_60_pos_red);...
    length(time40_60_pos_blue)]); ylim([0,45]);
title('Time 40-60 min');

figure;
subplot(1,3,1);
sgtitle('Exit events');
bar([1,2],[length(time0_20_neg_red);...
    length(time0_20_neg_blue)]); ylim([0,45]);
title('Time 2-20 min');
subplot(1,3,2);
bar([1,2],[length(time20_40_neg_red);...
    length(time20_40_neg_blue)]); ylim([0,45]);
title('Time 20-40 min');
subplot(1,3,3);
bar([1,2],[length(time40_60_neg_red);...
    length(time40_60_neg_blue)]); ylim([0,45]);
title('Time 40-60 min');

%% In vivo plots
% Amplitude distributions
figure;
subplot(2,1,1);
x = [rmoutliers(positive_amplitudes.PCP_4x_in_vivo);...
    rmoutliers(positive_amplitudes.PCP_24x_in_vivo)];
g1 = repmat({'PP7-4x-Qb-5x'},length(rmoutliers(positive_amplitudes.PCP_4x_in_vivo)),1);
g2 = repmat({'PP7-24x'},length(rmoutliers(positive_amplitudes.PCP_24x_in_vivo)),1);
g = [g1; g2;];
boxplot(x,g); ylim([0,1500]);
ylabel('Intensity [A.U]');

subplot(2,1,2);
x = [rmoutliers(negative_amplitudes.PCP_4x_in_vivo);...
    rmoutliers(negative_amplitudes.PCP_24x_in_vivo)];
g1 = repmat({'PP7-4x-Qb-5x'},length(rmoutliers(negative_amplitudes.PCP_4x_in_vivo)),1);
g2 = repmat({'PP7-24x'},length(rmoutliers(negative_amplitudes.PCP_24x_in_vivo)),1);
g = [g1; g2;];
boxplot(x,g); ylim([-1500,0]);
ylabel('Intensity [A.U]');

% Cell intensity measurements
figure;
x = [rmoutliers(PP7_RBP_ONLY_background);... % remove outliers for clearer plot
    in_vivo_mean_cell_intensity.PCP_4x_in_vivo;...
    in_vivo_mean_cell_intensity.PCP_24x_in_vivo];
g = [repmat({'PCP RBP only'},length(rmoutliers(PP7_RBP_ONLY_background)),1);...
    repmat({'PCP-4x'},length(in_vivo_mean_spot_intensity.PCP_4x_in_vivo),1);...
    repmat({'PCP-24x'},length(in_vivo_mean_spot_intensity.PCP_24x_in_vivo),1)];
boxplot(x,g); 
ylim([0,3.5e4]);
ylabel('Fluorescence intensity');
% Granule intensity measurements
figure;
x = [in_vivo_mean_spot_intensity.PCP_4x_in_vivo,...
    in_vivo_mean_spot_intensity.PCP_24x_in_vivo];
g = [repmat({'PCP-4x'},length(in_vivo_mean_spot_intensity.PCP_4x_in_vivo),1);...
    repmat({'PCP-24x'},length(in_vivo_mean_spot_intensity.PCP_24x_in_vivo),1)];
boxplot(x,g); 
ylim([0,3.5e4]);
ylabel('Fluorescence intensity');
% Time between significant events
x0 = [(duration_between_exit.PCP_4x_in_vivo);...
    (duration_between_entry.PCP_4x_in_vivo)];
g0 = [repmat({'Exit'},length(duration_between_exit.PCP_4x_in_vivo),1);...
    repmat({'Entry'},length(duration_between_entry.PCP_4x_in_vivo),1)];

x1 = [(duration_between_exit.PCP_24x_in_vivo);...
    (duration_between_entry.PCP_24x_in_vivo)];
g1 = [repmat({'Exit'},length(duration_between_exit.PCP_24x_in_vivo),1);...
    repmat({'Entry'},length(duration_between_entry.PCP_24x_in_vivo),1)];

figure;
subplot(1,2,1); boxplot(x0,g0,'Colors','rg'); ylim([0,60]); title('PP7-4x'); ylabel('Time [min]');
subplot(1,2,2); boxplot(x1,g1,'Colors','rg'); ylim([0,60]); title('PP7-24x'); 
