%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Script read_tables reads all the csv file in the current folder. Assuming
% the all the files were generated by the Mosiac ImageJ plugin, the script
% extracts the (trajectory,x,y,frame) data from each .csv file and saves 
% the data to a .mat file. The data is saved as a cell object in a cell
% array.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clear;
files = dir('*.csv');

for f = 1:numel(files)
    x = cell(1,1);
    y = cell(1,1);
    frame = cell(1,1);
    data = table2array(readtable(files(f).name));
    traj = data(:,2);
    numTraj = unique(traj);    
    for k = 1:max(numTraj)
        x = [x,{data(find(traj==k),4)}];
        y = [y,{data(find(traj==k),5)}];
        frame = [frame,{data(find(traj==k),3)}];
    end
    x = x(2:end);
    y = y(2:end);
    frame = frame(2:end);
    save([files(f).name(1:3),'_xy.mat'],'x','y','frame');
end